# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PGUSER", "") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: <%= ENV.fetch("PGDATABASE", "") %>

# test:
#   <<: *default
#   database: <%= ENV.fetch("PGDATABASE", "") %>

development:
  <<: *default
  database: br_archaeological_journals_development

test:
  <<: *default
  database: br_archaeological_journals_test

production:
  <<: *default
  database: br_archaeological_journals_production
  username: br_archaeological_journals
  password: <%= ENV["BR_ARCHAEOLOGICAL_JOURNALS_DATABASE_PASSWORD"] %>